### PR TITLE
[Sprint 251][MOB-1424][EFS][Android] Improve documentation of JAVA implementation with the mobile app

### PR DESCRIPTION
**Pull request by cjae**
## What did I do?
* Created Java implementations of the Kotlin code snippets on the README.md file.
---

## Deployment/Dependency Checklist:

* [ ] [List_out_any_new_ENV_vars]
* [ ] [List_out_any_back_end_dependencies]
---
## PR notes contain:
* [ ] Checklist for any deployment dependencies (such as new env vars, back-end dependencies, etc)
## PR Checklist:
* [ ] **I tested this**
* [x] I updated from the base branch (usually `latest`)
* [ ] I attached screenshot(s) (if there were UI changes)
* [x] I used the following PR title format: "[SPRINT-XX][fat-xx] BLAH"
  * Add "[EFS]" to the PR title if it was in the ticket title, e.g. "[SPRINT-XX][fat-xx][EFS]"
* [x] I looked over the Files Changed tab
* [ ] I consulted with the ticket's product owner (if necessary)
* [x] I requested a peer review

### CODE REVIEW

**Review by muryno — APPROVED** [review]
don't push your misc.xml local cache and same for modules

**Review by thomasvidas — CHANGES_REQUESTED** [review]
Remove the `.idea` files from the PR. Otherwise this is good!

**Comment by cjae** [comment]
> Remove the `.idea` files from the PR. Otherwise this is good!

Done

**Review by thomasvidas — CHANGES_REQUESTED** [review]
The files should not be added to the `.gitignore`. Remove the `.idea` files in this PR with `git rm` and remove the changes to the `.gitignore`

**Pull request closed without merging**
